export type ContentBlock =
  | { type: "paragraph"; text: string }
  | { type: "heading"; level: 2 | 3; text: string }
  | { type: "quote"; text: string; attribution?: string }
  | { type: "list"; items: string[] }
  | { type: "divider" };

export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  metaDescription: string;
  category: string;
  tags: string[];
  author: string;
  authorRole: string;
  date: string;
  dateISO: string;
  readTime: number;
  coverImage: string;
  coverAlt: string;
  featured?: boolean;
  content: ContentBlock[];
}

export const blogPosts: BlogPost[] = [
  {
    slug: "from-six-friends-to-global-brotherhood",
    title: "From Six Friends in Italy to a Global Brotherhood: The Story of the Moving Train",
    excerpt: "In 2020, a moment of grief in a foreign land became the catalyst for something extraordinary. Six Nigerian friends chose to transform their bond into a permanent institution — and the Moving Train was born.",
    metaDescription: "Discover the founding story of the Great Moving Train Social Club International — how six Nigerian friends in Italy built a global brotherhood in 2020 from a single moment of loss.",
    category: "History",
    tags: ["founding", "history", "Nigeria", "Italy", "brotherhood", "diaspora"],
    author: "Editorial Team",
    authorRole: "GMTSCI Media & Communications",
    date: "January 2025",
    dateISO: "2025-01-15",
    readTime: 7,
    coverImage: "/images/invite.jpg",
    coverAlt: "The first gathering of Moving Train members in Italy, 2020",
    featured: true,
    content: [
      { type: "paragraph", text: "Every great institution begins not with a plan, but with a feeling. For the Great Moving Train Social Club International, that feeling was grief — and what followed it was something remarkable: the decision to never face grief alone again." },
      { type: "heading", level: 2, text: "Italy, 2020: The Moment Everything Changed" },
      { type: "paragraph", text: "Six Nigerian men were living their lives abroad — building careers, raising families, navigating the particular solitude that comes with life far from home. Mr. Chinedu Okafor, Mr. Chinatu Ubani, Mr. John Matthew, Mr. Nnamdi Muodukwu, Mr. Chuks Ikwuakolam Omumu, and Mr. Daniel Anyaeri had found in each other something rare: a genuine friendship that endured across distances and differences." },
      { type: "paragraph", text: "When Mr. Daniel Anyaeri received news that his mother had passed away, the grief was immense. But what happened next was the true beginning of the Moving Train. Mr. Chinatu Ubani reached out to the other friends and made a proposal that would change all of their lives: let us form something permanent. A Committee of Friends — a structured, committed circle with explicit obligations to one another. Not a casual gathering, but a covenant." },
      { type: "quote", text: "Let us build something that ensures no brother ever faces life's hardest moments alone.", attribution: "Mr. Chinatu Ubani, Co-Founder" },
      { type: "heading", level: 2, text: "A Proposal That Was Met with Yes" },
      { type: "paragraph", text: "The unanimous agreement among those six men was not a small thing. It was a conscious choice to elevate friendship into responsibility. To say, in effect, that they would not merely care about one another in an abstract sense — they would show up. Financially. Emotionally. Consistently." },
      { type: "paragraph", text: "As the committee took shape, two more men were invited to join: Mr. Bertrand Chekwube Ugorji and Mr. Samson Ndenojuo. The circle grew from six to eight — but more than the number, what grew was the seriousness of purpose. These were men who understood that belonging to something meaningful required more than membership. It required character." },
      { type: "heading", level: 2, text: "Choosing a Name with Intention" },
      { type: "paragraph", text: "The name 'Moving Train' was not accidental. A train is not stationary. It does not pause for terrain, for weather, or for inconvenience. It moves forward, carrying all of its passengers together, accumulating momentum with every mile. The founders chose this image deliberately — because it expressed exactly what they intended to build." },
      { type: "paragraph", text: "The motto followed naturally: The Moving Train Never Stops Moving Forward. Not as an aspiration, but as a statement of identity. The organisation would not drift. It would not stall. Whatever the obstacles ahead, the train would keep moving." },
      { type: "heading", level: 2, text: "From Committee to International Organisation" },
      { type: "paragraph", text: "What began as an informal Committee of Friends evolved with remarkable speed. A constitution was drafted — a governance framework that would ensure transparency, fairness, and longevity. Executive positions were established. The club was formally registered with the Corporate Affairs Commission of Nigeria, giving it official legal recognition." },
      { type: "paragraph", text: "Today, the Great Moving Train Social Club International has members across Nigeria, Italy, Germany, the United Kingdom, and North America. Over ₦48 million in welfare benefits has been distributed. Three Chairmen have served. And in 2026, the club will hold its first international convention — a gathering that will bring the brotherhood face to face, across continents." },
      { type: "paragraph", text: "All of it traces back to one moment of grief, and one man's decision to do something about it." },
      { type: "divider" },
      { type: "paragraph", text: "The Moving Train story is not finished. Every new member who joins adds their chapter to an institution that was built to last — to outlast any single season, any individual, any circumstance. The train is still moving. And it is carrying all of its passengers forward together." },
    ],
  },
  {
    slug: "brotherhood-the-best-investment-nigerian-diaspora",
    title: "Brotherhood is the Best Investment a Nigerian in the Diaspora Can Make",
    excerpt: "Markets fluctuate. Properties depreciate. But a genuine circle of brothers — men committed to showing up in every season of life — compounds in ways no financial instrument can replicate.",
    metaDescription: "Why membership in a brotherhood like the Great Moving Train Social Club International is one of the most valuable investments for Nigerians living abroad.",
    category: "Philosophy",
    tags: ["diaspora", "investment", "welfare", "Nigeria abroad", "brotherhood", "community"],
    author: "Editorial Team",
    authorRole: "GMTSCI Media & Communications",
    date: "February 2025",
    dateISO: "2025-02-10",
    readTime: 6,
    coverImage: "/images/values/brotherhood.jpg",
    coverAlt: "Brotherhood — members in solidarity",
    content: [
      { type: "paragraph", text: "If you asked a Nigerian in the diaspora what their most valuable asset was, most would say property back home. Some would say their degree. A few might say their career. Almost none would say their people. And yet, when the most significant moments of life arrive — bereavement, illness, a child's wedding, a moment of acute financial pressure — it is not a property deed that shows up at the door." },
      { type: "heading", level: 2, text: "The Hidden Poverty of Life Abroad" },
      { type: "paragraph", text: "Life in Europe or North America as a Nigerian carries a specific kind of loneliness that is rarely spoken about directly. You may be professionally accomplished. You may live in a comfortable apartment. But when your mother dies in Nigeria and you need to organise a burial from three thousand miles away, you discover very quickly whether you have a real community or merely a collection of acquaintances." },
      { type: "paragraph", text: "The Nigerian social ecosystem — extended family, church, community groups, age grades — provides a safety net that those at home take for granted. Abroad, that net is absent or severely weakened. The Moving Train was founded precisely to rebuild it." },
      { type: "heading", level: 2, text: "What Brotherhood Actually Pays Out" },
      { type: "paragraph", text: "Since 2020, the Great Moving Train Social Club International has distributed over ₦48 million in welfare benefits to its members. That number includes financial contributions for weddings, bereavement, housewarmings, chieftaincy celebrations, medical emergencies, and milestone birthdays. But the figure barely captures what is actually being given." },
      { type: "list", items: [
        "Financial support during bereavement — covering the cost of burial arrangements members cannot manage alone",
        "Wedding contributions — ensuring that a member's most important day has the material support it deserves",
        "Birthday and milestone recognition — affirming members on significant occasions",
        "Emergency support — mobilising quickly when a brother faces an unexpected crisis",
        "Moral presence — showing up not just with money but with time and solidarity",
      ]},
      { type: "heading", level: 2, text: "The Compound Effect of Belonging" },
      { type: "paragraph", text: "Here is what distinguishes a brotherhood from a social club: a social club provides events. A brotherhood provides people. And people, unlike events, are available at 2am when the phone call comes with bad news." },
      { type: "quote", text: "When one member suffers, the brotherhood responds. When one succeeds, the brotherhood celebrates. This is not a rule — it is the spirit that animates everything the Moving Train does." },
      { type: "paragraph", text: "The return on this investment does not show up on a balance sheet. It shows up in the quality of a life lived with genuine support — in the knowledge that you are not navigating a foreign country alone, that your family will be cared for if something happens to you, that your achievements will be witnessed and celebrated by people who know your full story." },
      { type: "heading", level: 2, text: "Membership as Long-Term Strategy" },
      { type: "paragraph", text: "Those who join the Moving Train often describe the decision as one of the most consequential they have made — not because it was expensive or complicated, but because of what it unlocked. Not just financial support, but accountability. Not just social connection, but a governance framework that protects every member equally." },
      { type: "paragraph", text: "Brotherhood, properly organised and genuinely committed to, is the most resilient form of wealth a Nigerian abroad can accumulate. Markets fall. Governments change. But brothers who have made a covenant to one another — those compound differently." },
    ],
  },
  {
    slug: "what-moving-train-name-really-means",
    title: "The Moving Train: Why Our Name Is Also Our Philosophy",
    excerpt: "When the founders chose the name 'Moving Train', they were not simply naming an organisation. They were choosing an identity, a posture towards life, and a commitment that would define everything that followed.",
    metaDescription: "Explore the deep symbolism behind the name 'Moving Train' and the philosophy that drives the Great Moving Train Social Club International forward.",
    category: "Philosophy",
    tags: ["philosophy", "values", "identity", "motto", "progress", "Moving Train"],
    author: "Editorial Team",
    authorRole: "GMTSCI Media & Communications",
    date: "March 2025",
    dateISO: "2025-03-05",
    readTime: 5,
    coverImage: "/images/values/progress.png",
    coverAlt: "Progress — the Moving Train philosophy in motion",
    content: [
      { type: "paragraph", text: "Names reveal what we value. The name 'Moving Train' is not decorative — it is diagnostic. Every word in it carries deliberate weight, and together they define not just an organisation but a way of moving through the world." },
      { type: "heading", level: 2, text: "Why a Train?" },
      { type: "paragraph", text: "The founders could have chosen any symbol. They chose a train — and the choice was precise. A train operates according to fixed principles: it runs on rails, it carries passengers together, it does not deviate for individual convenience, and above all, it keeps moving. It does not have the luxury of stopping every time the terrain becomes difficult." },
      { type: "paragraph", text: "For men living abroad — navigating foreign systems, building lives far from home, managing the demands of diaspora existence — the train was the right image. It captured something they recognised in themselves: the refusal to be derailed by circumstance." },
      { type: "heading", level: 2, text: "The Word 'Moving' Does the Most Work" },
      { type: "paragraph", text: "Notice that the name does not say 'the Train'. It says 'the Moving Train'. The modifier is everything. A stationary train is a platform — a place to stand. A moving train is a vehicle — a means of getting somewhere." },
      { type: "paragraph", text: "The founders did not want to build a platform for gathering. They wanted to build a vehicle for forward motion. The distinction matters enormously in how the club operates. Every decision, every policy, every welfare contribution is oriented not just toward the present need but toward collective progress." },
      { type: "quote", text: "The Moving Train Never Stops Moving Forward.", attribution: "GMTSCI Motto" },
      { type: "heading", level: 2, text: "No Passenger Left Behind" },
      { type: "paragraph", text: "A train carries all of its passengers. It does not drop some at an inconvenient junction and continue with the rest. This is perhaps the most quietly radical aspect of the Moving Train philosophy: the commitment to collective progress means no brother is disposable, no circumstance is too inconvenient, no member faces a crisis without the full weight of the brotherhood behind them." },
      { type: "paragraph", text: "This is not sentimentality. It is structural. The constitution, the welfare system, the governance framework — all of it is designed to ensure that belonging to the Moving Train means something concrete and reliable, not merely symbolic." },
      { type: "heading", level: 2, text: "A Name That Sets the Standard" },
      { type: "paragraph", text: "One of the functions of a name is to create accountability. When you name yourself 'The Moving Train', you are making a public commitment to movement. Stagnation becomes a contradiction of identity. Inaction becomes impossible to justify. The name is a mirror that the organisation must live up to every day." },
      { type: "paragraph", text: "Five years on, the Moving Train is still moving. New members have joined the passenger list. New chapters are opening in new cities. And in 2026, the train will make one of its most significant stops yet — the first international convention, bringing all passengers together in one place for the first time. The destination keeps getting further and more interesting. That, ultimately, is the point." },
    ],
  },
  {
    slug: "cac-registration-official-recognition-nigeria",
    title: "CAC Registered: Why Formal Recognition Changed Everything for the Moving Train",
    excerpt: "When the Moving Train became officially registered with the Corporate Affairs Commission of Nigeria, it stopped being a circle of friends and became an institution. Here is what that step meant — and why it mattered.",
    metaDescription: "Learn how the Corporate Affairs Commission registration transformed the Great Moving Train Social Club International into a formally recognised Nigerian institution with legal standing.",
    category: "Milestones",
    tags: ["CAC", "registration", "Nigeria", "legal", "governance", "milestone", "institution"],
    author: "Editorial Team",
    authorRole: "GMTSCI Media & Communications",
    date: "April 2025",
    dateISO: "2025-04-12",
    readTime: 5,
    coverImage: "/images/CAC.jpg",
    coverAlt: "CAC Certificate of Registration — Great Moving Train Social Club International",
    content: [
      { type: "paragraph", text: "There is a difference between a group of people who care about each other and an institution that is built to last. The registration of the Great Moving Train Social Club International with the Corporate Affairs Commission of Nigeria was the moment that difference became real." },
      { type: "heading", level: 2, text: "What the CAC Registration Means" },
      { type: "paragraph", text: "The Corporate Affairs Commission is Nigeria's official body for the registration of companies, business names, and incorporated trustees. For a club or association, CAC registration confers formal legal identity — the organisation becomes a recognised entity under Nigerian law, with rights, responsibilities, and protections that informal groups simply do not have." },
      { type: "paragraph", text: "For the Moving Train, this was not a bureaucratic formality. It was a declaration of seriousness. By seeking official recognition, the founding members were communicating something important: this organisation is not temporary. It is not dependent on the goodwill of any individual. It exists — formally, legally, permanently — independent of the people who built it." },
      { type: "heading", level: 2, text: "The Member Who Made It Happen" },
      { type: "paragraph", text: "The facilitation of the club's CAC registration is one of the notable contributions in the Moving Train's history. It required navigating the complexities of Nigerian corporate registration, preparing the necessary documentation, coordinating with legal authorities, and seeing the process through to its conclusion — no small undertaking from abroad." },
      { type: "quote", text: "An organisation without legal standing is a hope. An organisation with legal standing is a fact.", },
      { type: "heading", level: 2, text: "What Registration Protects" },
      { type: "paragraph", text: "Formal registration creates a layer of accountability and protection that benefits every member. The organisation's assets, its governance structure, its financial records — all of these exist within a legal framework that cannot be dissolved by the departure of any single member or the changing of any personal relationship." },
      { type: "list", items: [
        "Members' welfare contributions are protected by a transparent governance framework",
        "The organisation can enter legal agreements and hold assets in its own name",
        "The club's identity persists across leadership transitions",
        "Official recognition lends credibility for future partnerships and growth",
        "Members can point to a formal institution when describing their membership to employers, banks, and official bodies",
      ]},
      { type: "heading", level: 2, text: "A Foundation for the Future" },
      { type: "paragraph", text: "The CAC certificate is more than a piece of paper. It is the foundation upon which every subsequent development of the Moving Train rests. The constitution, the welfare system, the executive structure, the annual accounts — all of it is supported by the fact of formal legal existence." },
      { type: "paragraph", text: "Organisations that last generations are not built on enthusiasm alone. They are built on structure, on documentation, on the kind of institutional seriousness that says: we are here, we are real, and we will still be here long after the individuals who started us are gone. The CAC registration was the Moving Train's commitment to that kind of longevity." },
    ],
  },
  {
    slug: "48-million-naira-member-welfare-benefits",
    title: "₦48 Million and Counting: The Real Financial Power of the Moving Train",
    excerpt: "Numbers tell a story. Over ₦48 million in welfare benefits distributed since 2020 is not just a figure — it is proof that when men of character commit to one another, the results are real and measurable.",
    metaDescription: "The Great Moving Train Social Club International has distributed over ₦48 million in member welfare benefits since its founding in 2020. Here is what that means for every member.",
    category: "Welfare",
    tags: ["welfare", "benefits", "₦48 million", "financial support", "members", "contributions"],
    author: "Editorial Team",
    authorRole: "GMTSCI Media & Communications",
    date: "May 2025",
    dateISO: "2025-05-08",
    readTime: 6,
    coverImage: "/images/why-join/financial-empowerment.png",
    coverAlt: "Financial empowerment through brotherhood membership",
    content: [
      { type: "paragraph", text: "When the founding members of the Moving Train proposed a Committee of Friends in 2020, the core promise was simple: no brother would face a significant life event without the financial and moral support of the group. Five years later, that promise has been honoured to the tune of over ₦48 million." },
      { type: "heading", level: 2, text: "Understanding What ₦48 Million Represents" },
      { type: "paragraph", text: "The ₦48 million figure is not a fundraising total or an investment balance. It is the sum of actual benefits paid out to members and their families — money that left the club's accounts and went directly to the moments in members' lives that mattered most. Burials organised. Weddings celebrated. Homes blessed at housewarming ceremonies. Medical emergencies addressed." },
      { type: "paragraph", text: "In the context of the Nigerian diaspora, where members are typically supporting families back home while managing the significant costs of life in Europe or North America, this financial backstop represents something profound. It means that a member who loses a parent does not have to choose between honouring their family and protecting their financial stability. The brotherhood absorbs some of that weight." },
      { type: "heading", level: 2, text: "Where the Money Goes" },
      { type: "list", items: [
        "Bereavement support — financial contributions toward burial arrangements and family care during loss",
        "Wedding gifts — meaningful contributions to a member's most significant celebration",
        "Housewarming support — recognising and marking major life transitions",
        "Birthday milestone contributions — formal recognition on significant birthdays",
        "Chieftaincy and title celebrations — honouring members as they achieve recognition in their communities",
        "Emergency welfare — rapid mobilisation for unforeseen crises",
      ]},
      { type: "heading", level: 2, text: "The Mathematics of Collective Commitment" },
      { type: "paragraph", text: "What makes the Moving Train's welfare system powerful is the principle behind it: consistent monthly dues from every member create a pool that no individual could sustain alone. This is not charity. It is collective self-insurance — a mechanism that makes the group stronger than the sum of its parts." },
      { type: "quote", text: "The strength of the wolf is the pack, and the strength of the pack is the wolf.", },
      { type: "paragraph", text: "Members who pay their dues consistently are not just fulfilling an obligation — they are building a resource that will be there for them when they need it. The member who contributes faithfully every month for three years has, in effect, purchased something no insurance policy offers: a network of people who will personally show up when the hard moments come." },
      { type: "heading", level: 2, text: "Toward ₦100 Million and Beyond" },
      { type: "paragraph", text: "The ₦48 million figure is a milestone, not a ceiling. As membership grows and the club's financial infrastructure matures, the capacity to support members increases proportionally. New chapters opening in new cities mean more contributors, more resources, and a wider safety net." },
      { type: "paragraph", text: "For prospective members, this number is perhaps the clearest argument for joining. It answers the question that every rational person asks before committing: does this actually work? The answer, backed by five years of consistent practice, is yes. Emphatically." },
    ],
  },
  {
    slug: "living-abroad-why-community-matters-nigeria-diaspora",
    title: "Living Abroad as a Nigerian: Why the Right Community Changes Everything",
    excerpt: "The Nigerian diaspora is one of the most accomplished communities in the world. It is also one of the loneliest. Here is why belonging to the right organisation transforms the experience of life outside Nigeria.",
    metaDescription: "Why community membership like the Great Moving Train Social Club International is essential for Nigerians living abroad — addressing diaspora loneliness, cultural identity, and mutual support.",
    category: "Community",
    tags: ["diaspora", "Nigeria abroad", "community", "loneliness", "identity", "support"],
    author: "Editorial Team",
    authorRole: "GMTSCI Media & Communications",
    date: "June 2025",
    dateISO: "2025-06-14",
    readTime: 6,
    coverImage: "/images/values/unity.jpg",
    coverAlt: "Unity among Nigerian diaspora members",
    content: [
      { type: "paragraph", text: "By almost every measure, Nigerians abroad are an extraordinary group. Nigerian-Americans are among the most educated immigrant communities in the United States. Nigerian professionals are embedded in the highest levels of British, Italian, and German institutions. The Nigerian diaspora sends home more remittances than any other African nation receives." },
      { type: "paragraph", text: "And yet, ask any Nigerian who has lived abroad for more than a few years, and they will describe a very specific kind of isolation. A sense of being professionally visible and personally invisible. Of succeeding in public while grieving privately. Of building a good life in a country that will never quite feel like home." },
      { type: "heading", level: 2, text: "What Gets Lost When You Leave" },
      { type: "paragraph", text: "Nigeria has a rich social infrastructure. Extended family networks. Church communities. Age grades and village unions. Neighbourhood solidarity. The informal systems through which Nigerians support one another in times of difficulty are deeply embedded in the culture — and they are largely absent abroad." },
      { type: "paragraph", text: "When you move to Italy or Germany or the United Kingdom, you take your work ethic with you. You take your ambition. But the communal safety net that would catch you in Nigeria — the uncles who show up unannounced, the church women who cook for a bereaved family, the neighbours who know your business and intervene when you need it — that does not travel with you." },
      { type: "quote", text: "Distance does not diminish the need for community. If anything, it amplifies it.", },
      { type: "heading", level: 2, text: "The Specific Challenges the Moving Train Addresses" },
      { type: "paragraph", text: "The Moving Train was not designed as a social club in the recreational sense. It was designed to address specific, concrete needs that Nigerians abroad face." },
      { type: "list", items: [
        "Bereavement abroad — when a parent dies in Nigeria, a member in Italy or Germany needs financial help, practical support, and people who understand what they are going through",
        "Cultural continuity — maintaining Nigerian identity and values while adapting to life abroad",
        "Trusted networks — having people you can call for professional referrals, housing advice, or urgent help",
        "Accountability — a structured community that holds members to their best selves",
        "Celebration — having people who genuinely rejoice with you at your milestones",
      ]},
      { type: "heading", level: 2, text: "The Quality of Connection Matters" },
      { type: "paragraph", text: "Not all community is equal. The Moving Train's particular value proposition is not just the existence of a group but the quality of the commitment within it. Members are not acquaintances who meet at occasional events. They are brothers who have made a formal covenant with one another — supported by a constitution, a welfare system, and a shared philosophy." },
      { type: "paragraph", text: "This distinction matters enormously in practice. Casual communities dissolve when life gets busy. Covenantal communities persist. The Moving Train was designed to be the latter — an organisation built not on enthusiasm but on structure, not on proximity but on commitment." },
      { type: "paragraph", text: "For any Nigerian living abroad who has felt the particular loneliness of diaspora life, the Moving Train offers something rare: a ready-made family, built on the same values you were raised with, ready to receive you." },
    ],
  },
  {
    slug: "constitution-governance-moving-train",
    title: "Built to Last: How the Moving Train's Constitution Protects Every Member",
    excerpt: "Great organisations are not held together by goodwill alone. They are held together by governance. The Moving Train's constitution is the document that transforms a circle of friends into an institution built for generations.",
    metaDescription: "How the Great Moving Train Social Club International's constitution and governance framework ensures transparency, fairness, and longevity for all members.",
    category: "Governance",
    tags: ["constitution", "governance", "transparency", "rules", "accountability", "institution"],
    author: "Editorial Team",
    authorRole: "GMTSCI Media & Communications",
    date: "July 2025",
    dateISO: "2025-07-03",
    readTime: 6,
    coverImage: "/images/values/accountability.jpg",
    coverAlt: "Accountability and governance in action",
    content: [
      { type: "paragraph", text: "There is a reason every enduring institution has a founding document. The United States has a Constitution. Professional bodies have charters. Universities have statutes. The document is not the institution — but without it, the institution cannot outlast the people who started it." },
      { type: "paragraph", text: "When the founding members of the Moving Train decided to draft a constitution, they were making a statement about the kind of organisation they intended to build: one that would survive any individual, any conflict, any season of difficulty." },
      { type: "heading", level: 2, text: "What a Constitution Actually Does" },
      { type: "paragraph", text: "A constitution is not merely a rulebook. It is a statement of values, a framework for decision-making, and a protection mechanism for every member. In the context of a welfare organisation, where real money and real relationships are involved, the importance of clear governance cannot be overstated." },
      { type: "list", items: [
        "It defines how decisions are made — so no single person can dominate",
        "It protects members' welfare contributions — so funds are used appropriately and transparently",
        "It establishes how leaders are selected — so authority is earned, not assumed",
        "It sets the terms of membership — so everyone knows their rights and responsibilities",
        "It creates a dispute resolution process — so conflicts are handled fairly",
        "It ensures the organisation persists across leadership changes — so members invest in an institution, not a personality",
      ]},
      { type: "heading", level: 2, text: "The People Who Built It" },
      { type: "paragraph", text: "The drafting of the Moving Train's constitution was one of its most significant early milestones. It required the kind of careful, collaborative work that does not happen quickly — thinking through scenarios, balancing different interests, and producing a document that every member could stand behind. The members who led this effort made a contribution to the club's longevity that is easy to underestimate." },
      { type: "quote", text: "A constitution is a love letter to the future. It says: we thought carefully about what we were building, and we wanted it to be good.", },
      { type: "heading", level: 2, text: "Transparency as a Value, Not Just a Policy" },
      { type: "paragraph", text: "One of the core values of the Moving Train is accountability — the commitment to being answerable for how power and resources are used. The constitution is the mechanism through which accountability is made real rather than merely rhetorical." },
      { type: "paragraph", text: "When a member contributes their monthly dues, they are entitled to know that those funds are being managed responsibly. When a benefit is paid, they are entitled to know it was paid in accordance with agreed criteria. When a decision is made, they are entitled to understand the process by which it was reached. The constitution guarantees all of this." },
      { type: "heading", level: 2, text: "Why This Matters for Every Member" },
      { type: "paragraph", text: "The existence of a robust governance framework is not just a technical matter. It is a source of confidence for every member. You can invest in the Moving Train — your time, your money, your trust — knowing that the institution is protected by structures that do not depend on any single individual remaining in power or in favour." },
      { type: "paragraph", text: "This is why the Moving Train is not just a club. It is an institution. And institutions, properly governed, outlast all of us." },
    ],
  },
  {
    slug: "from-grief-to-global-brotherhood-daniel-anyaeri",
    title: "How One Moment of Grief Gave Birth to an International Brotherhood",
    excerpt: "Loss has a way of revealing what truly matters. When Mr. Daniel Anyaeri's mother passed away in 2020, his friends could have simply sent condolences. Instead, they built something that would outlast all of them.",
    metaDescription: "The human story behind the founding of the Great Moving Train Social Club International — how grief became the catalyst for a global brotherhood in 2020.",
    category: "History",
    tags: ["founding", "grief", "Daniel Anyaeri", "2020", "origin", "brotherhood", "history"],
    author: "Editorial Team",
    authorRole: "GMTSCI Media & Communications",
    date: "August 2025",
    dateISO: "2025-08-20",
    readTime: 5,
    coverImage: "/images/values/compassion.jpg",
    coverAlt: "Compassion — the heart of the Moving Train",
    content: [
      { type: "paragraph", text: "We often speak of the Moving Train as an institution — with its constitution, its CAC registration, its ₦48 million in welfare contributions, its three Chairmen and growing membership across continents. But before any of that existed, there was a phone call. A piece of devastating news. And a group of friends who decided to respond in a way that changed all of their lives." },
      { type: "heading", level: 2, text: "The Call That Changed Everything" },
      { type: "paragraph", text: "In 2020, Mr. Daniel Anyaeri — one of six Nigerian friends living in Italy — received word that his mother had passed away. The grief was immediate and profound. But what followed it was something that would prove equally powerful: the response of his friends." },
      { type: "paragraph", text: "Mr. Chinatu Ubani, moved by both the loss itself and by a recognition of a deeper problem — that people living abroad face such moments without the communal infrastructure they would have had at home — made a proposal. Not just to support Daniel in this moment, but to build something that would support all of them in every moment like this, for the rest of their lives." },
      { type: "heading", level: 2, text: "The Anatomy of a Founding Moment" },
      { type: "paragraph", text: "What is remarkable about the Moving Train's origin is not just what was proposed, but how it was received. Six men, in the middle of their own busy lives, heard a proposal to formally commit to one another and said yes. Without hesitation. Without extended negotiation." },
      { type: "paragraph", text: "That response says something important about who these men were and what they understood about life. They recognised that the loneliness and vulnerability of diaspora life was not a personal failing to be managed individually. It was a structural condition that required a structural response." },
      { type: "quote", text: "Grief shows you who your real community is. If you don't have one, it shows you that too.", },
      { type: "heading", level: 2, text: "Transforming Pain into Architecture" },
      { type: "paragraph", text: "The decision these men made was not to merely provide comfort in the moment — it was to build an architecture that would prevent the sense of aloneness that makes moments of grief unbearable. A Committee of Friends. A structure with obligations. A framework for showing up." },
      { type: "paragraph", text: "Two additional members were invited to join — Mr. Bertrand Chekwube Ugorji and Mr. Samson Ndenojuo — expanding the circle and deepening the commitment. As the group grew, so did its intentionality. A name was chosen. A motto was adopted. A constitution was drafted. Legal registration was sought." },
      { type: "heading", level: 2, text: "What Mr. Anyaeri's Loss Made Possible" },
      { type: "paragraph", text: "It would be inappropriate to describe grief as a gift. But there is a truth that those who have been through significant loss often recognise: pain, when it is responded to with wisdom and intention, has the capacity to produce extraordinary things." },
      { type: "paragraph", text: "The Moving Train — with its global membership, its millions in welfare contributions, its upcoming convention, its constitution and governance and growing legacy — all of it traces back to a loss that happened in 2020 and a group of friends who refused to let that loss be the end of the story. They made it the beginning instead." },
    ],
  },
  {
    slug: "2026-convention-international-gathering",
    title: "The 2026 Convention: When the Moving Train Comes Together for the First Time",
    excerpt: "In 2026, members of the Great Moving Train Social Club International will gather from across the world for their first international convention. Here is why this moment is historic — and what it signals about the future.",
    metaDescription: "The Great Moving Train Social Club International's 2026 first international convention — what it means, why it matters, and what it signals for the future of the brotherhood.",
    category: "Events",
    tags: ["2026", "convention", "international", "gathering", "future", "milestone", "event"],
    author: "Editorial Team",
    authorRole: "GMTSCI Media & Communications",
    date: "September 2025",
    dateISO: "2025-09-11",
    readTime: 5,
    coverImage: "/images/zoom.jpg",
    coverAlt: "Moving Train international meeting — members connected across continents",
    content: [
      { type: "paragraph", text: "For five years, the Moving Train has operated across time zones, languages, and continents — united by a shared identity and supported by the technology of video calls, group messages, and digital welfare transfers. Members in Lagos have shown up for members in Rome. Brothers in London have supported brothers in New York. The connection has been real, even at distance." },
      { type: "paragraph", text: "But there is something that distance cannot replicate: the experience of being in the same room. Of hearing each other's laughter without a speaker. Of embracing a brother who has been a voice in your ear for years but a body you have never stood beside. The 2026 convention will provide that." },
      { type: "heading", level: 2, text: "Why Conventions Matter to Growing Organisations" },
      { type: "paragraph", text: "Every serious institution reaches a point where it must gather its people in physical space. Not because the work requires it — modern communication has made geographic distance nearly irrelevant for most organisational functions — but because community requires it. There is a depth of fellowship that only comes from shared physical presence: the shared meal, the formal ceremony, the informal conversation after the official programme ends." },
      { type: "paragraph", text: "For the Moving Train, the 2026 convention is also a coming-of-age moment. Five years of growth, documented and celebrated. Three Chairmen honoured. Members who have never met face to face discovering the full humanity of the names they have contributed alongside for years." },
      { type: "quote", text: "A convention is not just an event. It is the organisation becoming visible to itself.", },
      { type: "heading", level: 2, text: "What Members Can Expect" },
      { type: "paragraph", text: "The 2026 gathering will bring together members from Nigeria, Italy, Germany, the United Kingdom, North America, and beyond — a true international assembly of the brotherhood. It will feature formal sessions, the recognition of outstanding contributions, the celebration of milestones, and the kind of informal fellowship that cements relationships for decades." },
      { type: "list", items: [
        "Formal ceremony — honouring the founding members and the organisation's history",
        "Leadership recognition — acknowledging the three Chairmen who have served",
        "Welfare milestone celebration — marking the ₦48M+ in benefits distributed",
        "New member introductions — welcoming those who have joined since the founding",
        "Cultural programme — celebrating Nigerian heritage across the diaspora",
        "Strategic session — setting the direction for the next five years",
      ]},
      { type: "heading", level: 2, text: "The Significance for Membership" },
      { type: "paragraph", text: "For members who joined the Moving Train in its early years, the 2026 convention is a chance to see what they helped build. For newer members, it is the chance to understand — at a cellular level — what they belong to. And for prospective members watching from the outside, it is the clearest possible proof of concept: this is real, it is growing, and it is worth being part of." },
      { type: "paragraph", text: "The Moving Train never stops moving forward. In 2026, all passengers will board the same train at the same station, and for the first time, they will see just how far they have come." },
    ],
  },
  {
    slug: "welfare-weddings-funerals-showing-up",
    title: "Weddings, Funerals, and Everything Between: What It Really Means to Show Up",
    excerpt: "The Moving Train's welfare system covers the full spectrum of life's most significant moments. But behind the numbers and the policy language is something simpler: the commitment of men who have decided that showing up is not optional.",
    metaDescription: "How the Great Moving Train Social Club International's welfare system supports members through weddings, bereavements, housewarmings, and every significant life moment.",
    category: "Welfare",
    tags: ["welfare", "wedding", "bereavement", "support", "showing up", "community care"],
    author: "Editorial Team",
    authorRole: "GMTSCI Media & Communications",
    date: "October 2025",
    dateISO: "2025-10-09",
    readTime: 6,
    coverImage: "/images/why-join/strong-welfare-support.png",
    coverAlt: "Strong welfare support — the Moving Train cares for its members",
    content: [
      { type: "paragraph", text: "Life does not distribute its significant events evenly. Weddings and funerals, housewarmings and births, illness and recovery — these things arrive without warning and without regard for your financial preparation. What distinguishes people who navigate these moments well from those who are overwhelmed by them is almost always the same thing: community." },
      { type: "heading", level: 2, text: "The Philosophy of Showing Up" },
      { type: "paragraph", text: "The Moving Train's welfare system is built on a simple but powerful premise: the moments that matter most in a person's life should not be faced alone. This is not a new idea — it is, in fact, a very old Nigerian one. The Igbo tradition of 'oji', the practice of communal contributions at significant life events, is embedded in the cultural DNA of the club's founders and members." },
      { type: "paragraph", text: "What the Moving Train has done is to take that cultural instinct and give it structure, consistency, and cross-border reach. The result is a welfare system that works not because people feel obligated by social pressure, but because they have made a formal covenant with one another." },
      { type: "heading", level: 2, text: "The Moments the Brotherhood Covers" },
      { type: "list", items: [
        "Bereavement — when a member loses a parent, spouse, or child, the brotherhood mobilises both financially and personally",
        "Weddings — members receive formal contributions on their wedding day, with the brotherhood celebrating alongside",
        "Housewarmings — a member's first home in a new place is marked and blessed by the community",
        "Chieftaincy and title celebrations — cultural recognition is honoured as the significant achievement it is",
        "Milestone birthdays — significant birthdays are formally acknowledged and celebrated",
        "Medical emergencies — when unexpected health crises arise, members are not left to manage alone",
        "Family emergencies — the brotherhood responds to the full range of life's unexpected crises",
      ]},
      { type: "heading", level: 2, text: "What 'Showing Up' Looks Like in Practice" },
      { type: "paragraph", text: "The difference between a formal contribution and genuine showing up is not the amount — it is the intention behind it. When a Moving Train member receives welfare support from the brotherhood, they are not receiving a transaction. They are receiving the collective expression of care from dozens of people who, through their consistent monthly contributions, have been quietly building a resource for exactly this moment." },
      { type: "quote", text: "No member should face life's challenges alone. This is not a rule — it is the spirit that animates everything the Moving Train does.", attribution: "GMTSCI Philosophy" },
      { type: "heading", level: 2, text: "The Invisible Architecture of Care" },
      { type: "paragraph", text: "Most members will spend years contributing to the welfare pool without needing to draw from it heavily. This is not waste — it is investment. Every contribution is a building block in an architecture of care that will be there when it is needed. And when the hard moment comes — as it inevitably does for everyone — what members discover is not just money in an account, but people on the phone, and brothers willing to cross time zones to be present." },
      { type: "paragraph", text: "In the end, the welfare system is not about money at all. It is about what money represents when it comes from people who know your story, respect your journey, and have committed to being part of both. That is what the Moving Train offers. That is what showing up looks like, at scale." },
    ],
  },
];

export function getBlogPost(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug);
}

export function getRelatedPosts(slug: string, count = 3): BlogPost[] {
  return blogPosts.filter((p) => p.slug !== slug).slice(0, count);
}
